// Janes Jeans PrimeVue v4 preset — the P4 token mapping (real kit, full
// component surface). Builds on the P4a spike's proven mechanism: a
// `definePreset` leaf value that is a plain string (not one of PrimeVue's own
// `{a.b.c}` refs) is written VERBATIM as the corresponding `--p-*` custom
// property's value. `var(--kebab-token-id)` strings therefore make every
// `--p-*` var a pure indirection onto the kit's own CSS vars (generated by
// `npm run tokens` from `@metatoy/janes-jeans` into
// `src/tokens/generated/variables.css`) — confirmed again below by
// scripts/verify-live-swap.mjs against the full storefront, not just one Button.
//
// THE RECIPE (this is the "PrimeVue 3-tier token preset" §D asks for — no
// `SORB_PRIMEVUE` SD format exists yet, so the mapping lives HERE, at the
// preset layer, not in a Style Dictionary emit format). Two override tiers:
//
//   1. SEMANTIC tier overrides cascade for free. Most PrimeVue components
//      reference a small set of semantic roots (`primary`, `text`, `content`,
//      `formField`, `overlay.*`, `colorScheme.light.surface`) rather than
//      defining their own colors — overriding those ~6 roots re-themes Card,
//      InputText, Select's overlay, Dialog, Toast's border/bg-normal, Tabs,
//      Accordion, DataTable, DatePicker, DataView, etc. all at once.
//   2. COMPONENT tier overrides for the few things that read straight from
//      the PRIMITIVE palette (`{green.500}`, `{sky.100}`, …) instead of a
//      semantic root — PrimeVue's severity-colored Tag/Toast — where the kit
//      has an exact analog (`toast.bg.success/danger/info`) or needs an
//      explicit per-component override (Menubar's brand-colored bar; the
//      kit's `nav.*` tokens are a DIFFERENT color story than the
//      content/surface tokens used everywhere else, by design — the top nav
//      bar is the one brand-saturated surface in the storefront).
//
// See CLAUDE.md's "Migration recipe" section for the full literal→token
// mapping table (this file's hardcoded values BEFORE `sorb-migrated`, tag
// `pre-sorb`, are preserved there for the record).
import { definePreset } from '@primeuix/themes'
import Aura from '@primeuix/themes/aura'

const v = (id) => `var(--${id})`

export const JJPreset = definePreset(Aura, {
  semantic: {
    primary: {
      color: v('button-primary-bg-default'),
      hoverColor: v('button-primary-bg-hover'),
      activeColor: v('button-primary-bg-hover'),
      contrastColor: v('button-primary-fg-default'),
    },
    text: {
      color: v('color-ink'),
      hoverColor: v('color-ink'),
      mutedColor: v('color-ink-muted'),
      hoverMutedColor: v('color-ink-muted'),
    },
    content: {
      background: v('card-bg'),
      hoverBackground: v('color-surface-raised'),
      borderColor: v('card-border'),
      color: v('color-ink'),
      hoverColor: v('color-ink'),
      borderRadius: v('card-radius'),
    },
    formField: {
      background: v('input-bg-default'),
      disabledBackground: v('input-bg-disabled'),
      filledBackground: v('input-bg-default'),
      filledHoverBackground: v('input-bg-default'),
      filledFocusBackground: v('input-bg-default'),
      borderColor: v('input-border-default'),
      hoverBorderColor: v('input-border-default'),
      focusBorderColor: v('input-border-focus'),
      invalidBorderColor: v('input-border-invalid'),
      color: v('input-fg'),
      disabledColor: v('color-ink-muted'),
      placeholderColor: v('input-placeholder'),
      invalidPlaceholderColor: v('input-placeholder'),
      borderRadius: v('input-radius'),
    },
    navigation: {
      item: {
        activeColor: v('nav-link-active'),
        focusColor: v('nav-link-active'),
      },
    },
    overlay: {
      select: { background: v('card-bg'), borderColor: v('card-border'), color: v('color-ink') },
      popover: { background: v('card-bg'), borderColor: v('card-border'), color: v('color-ink') },
      modal: { background: v('card-bg'), borderColor: v('card-border'), color: v('color-ink') },
    },
    colorScheme: {
      light: {
        surface: {
          50: v('color-surface-raised'),
          100: v('color-surface-raised'),
          200: v('color-surface-sunken'),
          300: v('color-border'),
        },
      },
    },
  },
  components: {
    // The brand-colored top bar — the one place the kit's nav.* tokens
    // (distinct from the content/surface story used everywhere else) apply.
    menubar: {
      colorScheme: {
        light: {
          root: { background: v('nav-bg'), borderColor: v('nav-bg'), color: v('nav-fg') },
          item: {
            color: v('nav-fg'),
            focusColor: v('nav-link-active'),
            activeColor: v('nav-link-active'),
            icon: { color: v('nav-fg-muted'), focusColor: v('nav-link-active'), activeColor: v('nav-link-active') },
          },
        },
      },
    },
    // Toast severities: the kit defines success/danger/info (no "warn" — the
    // storefront never triggers one); PrimeVue's default "warn" stays themed
    // by the semantic `content`/`text` overrides above (not brand-perfect,
    // but never exercised, so undocumented drift risk is zero).
    toast: {
      colorScheme: {
        light: {
          success: { background: v('toast-bg-success'), color: v('toast-fg'), borderColor: v('toast-bg-success') },
          error: { background: v('toast-bg-danger'), color: v('toast-fg'), borderColor: v('toast-bg-danger') },
          info: { background: v('toast-bg-info'), color: v('toast-fg'), borderColor: v('toast-bg-info') },
        },
      },
    },
  },
})
