// Non-React sorbConfig — full kit-token pipeline (P4). `tokens` is the
// COMMITTED set generated by `npm run tokens` from @metatoy/janes-jeans (via
// sd.config.js) — real DTCG tokens, not the P4a spike's 6 hand-authored vars.
//
// GOTCHA (carried from the P4a spike report, applies here too): every key in
// `tokens` — and every key in any preview body POSTed/PUT to the bridge — is
// a BARE id, no leading `--`. `applyTokens` (sorb-leaf/src/apply.js) does
// `root.style.setProperty(\`--${key}\`, value)` itself.
import { tokens } from './tokens/generated/tokens.js'

export const sorbConfig = {
  namespace: 'jj-primevue',
  tokens,
  preview: {
    enabled: true,
    origin: 'http://127.0.0.1:7784',
    pollInterval: 1000,
    // Vocabulary guard: the kit's token ids carry no stack/brand prefix (by
    // design — see @metatoy/janes-jeans's neutrality rule), so there's no
    // single "jj-" prefix to check like the spike used. Instead list the
    // dominant families this store actually renders from — a preview whose
    // keys match NONE of these is very likely aimed at the wrong project.
    expectPrefixes: ['color-', 'button-', 'card-', 'badge-', 'input-', 'nav-', 'toast-', 'radius-'],
  },
}
